@Server_HostAddress = https://localhost:54782

GET {{Server_HostAddress}}/api/test/
Response-Type: application/json

###

GET {{Server_HostAddress}}/api/testdb/
Response-Type: application/json

###

POST {{Server_HostAddress}}/api/testcreatedbmodel/
Response-Type: application/json

###